//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymGenius.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GymGenius.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Abdominal exercises, commonly known as core exercises, target the muscles in the abdomen, including the rectus abdominis, obliques, and transverse abdominis. These exercises help strengthen the core, improve posture, and enhance overall stability, contributing to better athletic performance and reduced risk of injury. Popular examples include crunches, planks, and leg raises..
        /// </summary>
        internal static string AbdominalsDescription_EN {
            get {
                return ResourceManager.GetString("AbdominalsDescription_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les abdominaux consistent en des mouvements tels que les &quot;crunches&quot; ou &quot;sit-ups&quot;, ciblant spécifiquement les muscles abdominaux pour renforcer la région centrale du corps. Ces exercices contribuent à améliorer la stabilité et la force du noyau..
        /// </summary>
        internal static string AbdominalsDescription_FR {
            get {
                return ResourceManager.GetString("AbdominalsDescription_FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Abdominals.
        /// </summary>
        internal static string AbdominalsName_EN {
            get {
                return ResourceManager.GetString("AbdominalsName_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Abdominaux.
        /// </summary>
        internal static string AbdominalsName_FR {
            get {
                return ResourceManager.GetString("AbdominalsName_FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fitness Mat.
        /// </summary>
        internal static string FitnessMatName_EN {
            get {
                return ResourceManager.GetString("FitnessMatName_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tapis de fitness.
        /// </summary>
        internal static string FitnessMatName_FR {
            get {
                return ResourceManager.GetString("FitnessMatName_FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Push-ups are a versatile strength training exercise in the sports domain, targeting upper body muscles including shoulders, triceps, and the core abdomen. This plank exercise, adaptable to different fitness levels, contributes to improving functional strength and stability..
        /// </summary>
        internal static string PushUpsDescription_EN {
            get {
                return ResourceManager.GetString("PushUpsDescription_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les pompes sont un exercice de musculation polyvalent dans le domaine sportif, renforçant les muscles du haut du corps, y compris les épaules, les triceps et le noyau abdominal. Cet exercice de planche, qui peut être adapté en fonction du niveau de fitness, contribue à améliorer la force fonctionnelle et la stabilité..
        /// </summary>
        internal static string PushUpsDescription_FR {
            get {
                return ResourceManager.GetString("PushUpsDescription_FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Push-ups.
        /// </summary>
        internal static string PushUpsName_EN {
            get {
                return ResourceManager.GetString("PushUpsName_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pompes.
        /// </summary>
        internal static string PushUpsName_FR {
            get {
                return ResourceManager.GetString("PushUpsName_FR", resourceCulture);
            }
        }
    }
}
